image: docker:stable

stages:
  - build
  - deploy

before_script:
- docker info

build:
  stage: build
  script:
    - docker build -t registry.skyloud.net/random/whiteboard .

deploy_staging:
  variables:
    DOCKER_PORT: 5001:5001

  stage: deploy
  only:
    - develop
  script:
    - docker rm -f prod-whiteboard 2>/dev/null || true
    - docker run -d -p $DOCKER_PORT --name prod-whiteboard registry.skyloud.net/random/whiteboard
  environment:
    name: staging
    url: https://www.skyloud.fr:5001

deploy_production:
  variables:
    DOCKER_PORT: 5001:5001
  stage: deploy
  only:
    - master
  script:
    - docker rm -f prod-whiteboard 2>/dev/null || true
    - docker run -d -p $DOCKER_PORT --name prod-whiteboard registry.skyloud.net/random/whiteboard
  environment:
    name: production
    url: https://www.skyloud.fr:5001
